import { Client, LocalAuth, MessageMedia } from "whatsapp-web.js";
import Tenant from "../models/Tenant";
import Customer from "../models/Customer";
import Invoice from "../models/Invoice";

const clients = new Map<string, Client>();
export const whatsappStatus = new Map<string, boolean>();

// ─── Get or create WhatsApp client per tenant ────────────────────────────────

export const getOrCreateClient = (tenantId: string) => {
  if (clients.has(tenantId)) {
    return clients.get(tenantId)!;
  }

  const client = new Client({
    authStrategy: new LocalAuth({ clientId: tenantId }),
  });

  client.on("qr", () => {
    console.log(`QR Generated For Tenant ${tenantId}`);
  });

  client.on("authenticated", () => {
    console.log(`WhatsApp Authenticated For Tenant ${tenantId}`);
  });

  client.on("ready", async () => {
    whatsappStatus.set(tenantId, true);
    await Tenant.findByIdAndUpdate(tenantId, { whatsappConnected: true });
    console.log(`WhatsApp Ready For Tenant ${tenantId}`);
  });

  client.on("auth_failure", (msg) => {
    console.log(`Auth Failed: ${msg}`);
  });

  client.on("disconnected", async (reason) => {
    whatsappStatus.set(tenantId, false);
    await Tenant.findByIdAndUpdate(tenantId, { whatsappConnected: false });
    clients.delete(tenantId);
    console.log(`Disconnected: ${reason}`);
  });

  client.initialize();
  clients.set(tenantId, client);
  return client;
};

// ─── Format phone number for WhatsApp ────────────────────────────────────────
// WhatsApp needs: 91XXXXXXXXXX@c.us (India)

const formatPhone = (phone: string): string => {
  const digits = phone.replace(/\D/g, "");
  // Add country code if not present
  const withCountry = digits.startsWith("91") ? digits : `91${digits}`;
  return `${withCountry}@c.us`;
};

// ─── Core send function ───────────────────────────────────────────────────────

export const sendWhatsAppMessage = async (
  tenantId: string,
  phone: string,
  message: string
): Promise<{ success: boolean; error?: string }> => {
  try {
    const tenant = await Tenant.findById(tenantId);
    if (!tenant?.whatsappConnected) {
      return { success: false, error: "WhatsApp not connected" };
    }

    const client = clients.get(tenantId);
    if (!client) {
      return { success: false, error: "WhatsApp client not found" };
    }

    const chatId = formatPhone(phone);
    await client.sendMessage(chatId, message);

    return { success: true };
  } catch (error: any) {
    console.error(`WhatsApp send error for tenant ${tenantId}:`, error);
    return { success: false, error: error.message };
  }
};

// ─── Message Templates ────────────────────────────────────────────────────────

export const buildInvoiceMessage = (
  companyName: string,
  customerName: string,
  invoiceNumber: string,
  grandTotal: number,
  invoiceDate: string
): string => {
  return (
    `Hello *${customerName}*,\n\n` +
    `Your invoice has been generated by *${companyName}*.\n\n` +
    `📄 *Invoice Details:*\n` +
    `• Invoice No: *${invoiceNumber}*\n` +
    `• Date: *${invoiceDate}*\n` +
    `• Amount: *₹${grandTotal.toFixed(2)}*\n\n` +
    `Please make the payment at your earliest convenience.\n\n` +
    `_This is an automated message from RateFlow ERP._`
  );
};

export const buildPaymentReceivedMessage = (
  companyName: string,
  customerName: string,
  invoiceNumber: string,
  paidAmount: number,
  outstandingAmount: number,
  paymentMode: string
): string => {
  const outstandingLine =
    outstandingAmount > 0
      ? `• Outstanding Balance: *₹${outstandingAmount.toFixed(2)}*\n`
      : `• Status: *Fully Paid ✅*\n`;

  return (
    `Hello *${customerName}*,\n\n` +
    `We have received your payment. Thank you! 🙏\n\n` +
    `💰 *Payment Details:*\n` +
    `• Invoice No: *${invoiceNumber}*\n` +
    `• Amount Received: *₹${paidAmount.toFixed(2)}*\n` +
    `• Mode: *${paymentMode}*\n` +
    outstandingLine +
    `\n_This is an automated message from ${companyName} via RateFlow ERP._`
  );
};

export const buildOutstandingReminderMessage = (
  companyName: string,
  customerName: string,
  outstandingAmount: number,
  pendingInvoices: { invoiceNumber: string; amount: number }[]
): string => {
  const invoiceLines = pendingInvoices
    .slice(0, 5) // max 5 invoices in message
    .map((inv) => `  • Invoice #${inv.invoiceNumber}: ₹${inv.amount.toFixed(2)}`)
    .join("\n");

  const moreText =
    pendingInvoices.length > 5
      ? `\n  ...and ${pendingInvoices.length - 5} more invoices`
      : "";

  return (
    `Hello *${customerName}*,\n\n` +
    `This is a friendly reminder from *${companyName}*.\n\n` +
    `📋 *Outstanding Payment Details:*\n` +
    invoiceLines +
    moreText +
    `\n\n💰 *Total Outstanding: ₹${outstandingAmount.toFixed(2)}*\n\n` +
    `Kindly clear your dues at the earliest.\n\n` +
    `_This is an automated reminder from RateFlow ERP._`
  );
};

// ─── Scheduled: Send outstanding reminders every 15 days ─────────────────────
// Call this from a cron job in index.ts

export const sendOutstandingReminders = async () => {
  console.log("Running 15-day outstanding reminder job...");

  try {
    // Get all tenants with WhatsApp connected
    const tenants = await Tenant.find({ whatsappConnected: true });

    for (const tenant of tenants) {
      const tenantId = tenant._id.toString();

      // Get all customers of this tenant with outstanding > 0
      const customers = await Customer.find({
        tenantId,
        outstandingAmount: { $gt: 0 },
        isDefault: false,
        phone: { $ne: "", $exists: true },
      });

      for (const customer of customers) {
        if (!customer.phone) continue;

        // Get pending invoices for this customer
        const pendingInvoices = await Invoice.find({
          tenantId,
          customerId: customer._id,
          paymentStatus: { $in: ["Pending", "Partial"] },
        }).select("invoiceNumber outstandingAmount");

        if (pendingInvoices.length === 0) continue;

        const message = buildOutstandingReminderMessage(
          tenant.companyName,
          customer.name,
          customer.outstandingAmount,
          pendingInvoices.map((inv) => ({
            invoiceNumber: inv.invoiceNumber,
            amount: inv.outstandingAmount,
          }))
        );

        const result = await sendWhatsAppMessage(
          tenantId,
          customer.phone,
          message
        );

        if (result.success) {
          console.log(`Reminder sent to ${customer.name} (${customer.phone})`);
        } else {
          console.log(`Failed for ${customer.name}: ${result.error}`);
        }

        // Small delay between messages to avoid spam detection
        await new Promise((r) => setTimeout(r, 1500));
      }
    }
  } catch (error) {
    console.error("Outstanding reminder job error:", error);
  }
};